name: Michael Latta 
title: Michael Latta
description: "Student"

defaults: 
  - 
    scope: 
      path: "" # an empty string here means all files in the project 
    values: 
      layout: "default"
